# Generated by Django 5.2.15 on 2026-06-04 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CaseStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Case Study Title')),
                ('description', models.TextField(verbose_name='Description / Summary')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='case_studies/', verbose_name='PDF Document')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='case_studies/thumbnails/', verbose_name='Thumbnail Image')),
                ('live_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='External Link (if any)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Display Order')),
            ],
            options={
                'verbose_name': 'Case Study',
                'verbose_name_plural': 'Case Studies',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Certification Name')),
                ('issuer', models.CharField(max_length=200, verbose_name='Issuing Organization')),
                ('issue_date', models.CharField(blank=True, max_length=50, verbose_name='Issue Date')),
                ('credential_url', models.URLField(blank=True, null=True, verbose_name='Credential URL')),
                ('image', models.ImageField(blank=True, null=True, upload_to='certifications/', verbose_name='Certificate Image')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Display Order')),
            ],
            options={
                'verbose_name': 'Certification',
                'verbose_name_plural': 'Certifications',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Project Name')),
                ('description', models.TextField(verbose_name='Project Description')),
                ('github_url', models.URLField(blank=True, null=True, verbose_name='GitHub Repository URL')),
                ('live_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='Live URL / Demo')),
                ('status', models.CharField(blank=True, choices=[('completed', 'Completed'), ('in_progress', 'In Progress'), ('live', 'Live'), ('archived', 'Archived')], max_length=20, null=True, verbose_name='Project Status')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Display Order')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProjectFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300, verbose_name='Feature Description')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Display Order')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='projects.project', verbose_name='Project')),
            ],
            options={
                'verbose_name': 'Project Feature',
                'verbose_name_plural': 'Project Features',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProjectScreenshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='projects/screenshots/', verbose_name='Screenshot Image')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='Caption')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Display Order')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenshots', to='projects.project', verbose_name='Project')),
            ],
            options={
                'verbose_name': 'Project Screenshot',
                'verbose_name_plural': 'Project Screenshots',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProjectTechnology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Technology Name')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technologies', to='projects.project', verbose_name='Project')),
            ],
            options={
                'verbose_name': 'Project Technology',
                'verbose_name_plural': 'Project Technologies',
            },
        ),
    ]
