# Generated by Django 5.2.15 on 2026-06-04 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=200, verbose_name='Job Role / Title')),
                ('organization', models.CharField(max_length=200, verbose_name='Organization / Company')),
                ('dates', models.CharField(max_length=200, verbose_name='Employment Dates')),
                ('responsibilities', models.TextField(verbose_name='Role Description / Responsibilities')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Display Order')),
            ],
            options={
                'verbose_name': 'Experience',
                'verbose_name_plural': 'Experience Records',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Achievement Text')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Display Order')),
                ('experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='experience.experience', verbose_name='Experience')),
            ],
            options={
                'verbose_name': 'Achievement',
                'verbose_name_plural': 'Achievements',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ExperienceTechnology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Technology / Tool')),
                ('experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technologies', to='experience.experience', verbose_name='Experience')),
            ],
            options={
                'verbose_name': 'Experience Technology',
                'verbose_name_plural': 'Experience Technologies',
            },
        ),
    ]
