# Generated by Django 5.2.15 on 2026-06-04 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Skill Name')),
                ('category', models.CharField(choices=[('tools_platforms', 'Tools & Platforms'), ('languages_frameworks', 'Languages & Frameworks'), ('technical_concepts', 'Technical Concepts')], max_length=50, verbose_name='Category')),
                ('proficiency', models.PositiveIntegerField(default=80, help_text='Enter a value between 0 and 100', verbose_name='Proficiency (%)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Display Order')),
            ],
            options={
                'verbose_name': 'Skill',
                'verbose_name_plural': 'Skills',
                'ordering': ['category', 'order', 'name'],
            },
        ),
    ]
