# Generated by Django 5.2.15 on 2026-06-04 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(max_length=200, verbose_name='Degree / Qualification')),
                ('institution', models.CharField(max_length=300, verbose_name='Institution Name')),
                ('start_year', models.CharField(max_length=10, verbose_name='Start Year')),
                ('end_year', models.CharField(blank=True, help_text="Leave blank or write 'Present' if currently enrolled", max_length=10, verbose_name='End Year')),
                ('gpa', models.CharField(blank=True, max_length=10, null=True, verbose_name='GPA / Grade')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description / Coursework')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Display Order')),
            ],
            options={
                'verbose_name': 'Education',
                'verbose_name_plural': 'Education Records',
                'ordering': ['order', '-start_year'],
            },
        ),
    ]
