# Generated by Django 5.2.15 on 2026-06-04 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='Full Name')),
                ('professional_title', models.CharField(max_length=200, verbose_name='Professional Title')),
                ('tagline', models.CharField(blank=True, max_length=300, verbose_name='Tagline')),
                ('bio', models.TextField(verbose_name='Short Bio')),
                ('about_section', models.TextField(verbose_name='About Section Content')),
                ('email', models.EmailField(max_length=254, verbose_name='Email Address')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Phone Number')),
                ('location', models.CharField(blank=True, max_length=100, verbose_name='Location')),
                ('linkedin_url', models.URLField(blank=True, verbose_name='LinkedIn URL')),
                ('github_url', models.URLField(blank=True, verbose_name='GitHub URL')),
                ('portfolio_url', models.URLField(blank=True, verbose_name='Portfolio URL')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='bio/', verbose_name='Profile Image')),
                ('resume_file', models.FileField(blank=True, null=True, upload_to='resume/', verbose_name='Resume (PDF)')),
            ],
            options={
                'verbose_name': 'Bio',
                'verbose_name_plural': 'Bio',
            },
        ),
    ]
